[project]
name = "app-estudios-trading"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "plotly>=6.5.2",
    "streamlit>=1.53.0",
    "lxml>=5.3.0",
    "scipy>=1.15.0",
]
